{
 "title": "Swyft Counter Dashboard",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "API Upload",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(api_upload_http_requests_total[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(increase(api_upload_http_requests_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Manual Upload",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(manual_upload_http_requests_total[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(increase(manual_upload_http_requests_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bulk Upload",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(increase(bulk_upload_http_requests_total[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(increase(bulk_upload_http_requests_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Test Counter",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum(increase(test_counter_http_requests_total[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(increase(test_counter_http_requests_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}